# Generated by Django 5.0.4 on 2026-04-26 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapilm_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_profile_complete',
            field=models.BooleanField(default=False, help_text='يصبح True عند تعيين الاسم لأول مرة', verbose_name='الملف مكتمل'),
        ),
    ]
