# Generated by Django 5.0.4 on 2026-04-26 20:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('body', models.CharField(max_length=1000, verbose_name='المحتوى')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية')),
                ('is_sent', models.BooleanField(default=False, verbose_name='أُرسلت')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الإرسال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'سجل إشعار',
                'verbose_name_plural': 'سجلات الإشعارات',
                'db_table': 'notification_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
