# Generated by Django 5.0.4 on 2026-04-26 20:35

import cloudinary.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('private', 'خاصة'), ('group', 'مجموعة')], default='private', max_length=10, verbose_name='النوع')),
                ('name', models.CharField(blank=True, help_text='للمجموعات فقط', max_length=120, verbose_name='الاسم')),
                ('avatar', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='avatar')),
                ('is_archived', models.BooleanField(default=False, verbose_name='مؤرشفة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'محادثة',
                'verbose_name_plural': 'المحادثات',
                'db_table': 'conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'عضو'), ('admin', 'مشرف')], default='member', max_length=10, verbose_name='الدور')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_read_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر قراءة')),
                ('is_muted', models.BooleanField(default=False, verbose_name='كتم الإشعارات')),
            ],
            options={
                'verbose_name': 'عضو في المحادثة',
                'verbose_name_plural': 'أعضاء المحادثة',
                'db_table': 'conversation_members',
                'ordering': ['joined_at'],
            },
        ),
    ]
