# Generated by Django 5.0.4 on 2026-04-26 20:35

import cloudinary.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mapilm_conversations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', cloudinary.models.CloudinaryField(max_length=255, verbose_name='ملف الوسائط')),
                ('file_type', models.CharField(choices=[('image', 'صورة'), ('voice', 'صوت')], max_length=10, verbose_name='نوع الملف')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='حجم الملف (bytes)')),
                ('duration', models.FloatField(blank=True, help_text='للرسائل الصوتية فقط', null=True, verbose_name='المدة (ثانية)')),
                ('thumbnail', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='الصورة المصغّرة')),
            ],
            options={
                'verbose_name': 'وسائط',
                'verbose_name_plural': 'الوسائط',
                'db_table': 'media',
            },
        ),
        migrations.CreateModel(
            name='MessageStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delivered', models.BooleanField(default=False, verbose_name='مُسلَّمة')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروءة')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت التسليم')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت القراءة')),
            ],
            options={
                'verbose_name': 'حالة رسالة',
                'verbose_name_plural': 'حالات الرسائل',
                'db_table': 'message_statuses',
                'ordering': ['message', 'user'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('text', 'نص'), ('image', 'صورة'), ('voice', 'صوت')], default='text', max_length=10, verbose_name='النوع')),
                ('content', models.TextField(blank=True, help_text='النص مشفّر (AES-256)', verbose_name='المحتوى')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='محذوف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mapilm_conversations.conversation', verbose_name='المحادثة')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='mapilm_messages.message', verbose_name='ردّ على')),
            ],
            options={
                'verbose_name': 'رسالة',
                'verbose_name_plural': 'الرسائل',
                'db_table': 'messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
